import type { AdherenceRecord, AdherenceSummary, Drug, User, VideoMetadata } from '@arys-rx/types';

export const MOCK_DRUGS: Drug[] = [
  {
    id: 'drug-001',
    name: 'Humira',
    genericName: 'adalimumab',
    manufacturer: 'AbbVie',
    requiresVideoAdherence: true,
    dosageInstructions: 'Inject subcutaneously every other week',
  },
  {
    id: 'drug-002',
    name: 'Enbrel',
    genericName: 'etanercept',
    manufacturer: 'Amgen',
    requiresVideoAdherence: true,
    dosageInstructions: 'Inject subcutaneously once weekly',
  },
];

export const MOCK_SUBSCRIBER: User = {
  id: 'user-sub-001',
  email: 'jane.doe@example.com',
  firstName: 'Jane',
  lastName: 'Doe',
  role: 'subscriber',
  createdAt: '2024-01-15T00:00:00Z',
};

export const MOCK_HR_USER: User = {
  id: 'user-hr-001',
  email: 'hr@acme.com',
  firstName: 'Chris',
  lastName: 'Taylor',
  role: 'hr',
  createdAt: '2024-01-01T00:00:00Z',
};

export const MOCK_PBM_USER: User = {
  id: 'user-pbm-001',
  email: 'analyst@caremark.com',
  firstName: 'Alex',
  lastName: 'Rivera',
  role: 'pbm',
  createdAt: '2024-01-01T00:00:00Z',
};

export const MOCK_ADHERENCE_RECORDS: AdherenceRecord[] = [
  {
    id: 'rec-001',
    subscriberId: 'user-sub-001',
    drugId: 'drug-001',
    drugName: 'Humira',
    scheduledAt: '2024-04-08T08:00:00Z',
    takenAt: '2024-04-08T08:12:00Z',
    status: 'taken',
    videoId: 'vid-001',
    notes: null,
  },
  {
    id: 'rec-002',
    subscriberId: 'user-sub-001',
    drugId: 'drug-001',
    drugName: 'Humira',
    scheduledAt: '2024-03-25T08:00:00Z',
    takenAt: '2024-03-25T09:01:00Z',
    status: 'taken',
    videoId: 'vid-002',
    notes: null,
  },
  {
    id: 'rec-003',
    subscriberId: 'user-sub-001',
    drugId: 'drug-001',
    drugName: 'Humira',
    scheduledAt: '2024-03-11T08:00:00Z',
    takenAt: null,
    status: 'missed',
    videoId: null,
    notes: 'Reported travel',
  },
  {
    id: 'rec-004',
    subscriberId: 'user-sub-001',
    drugId: 'drug-001',
    drugName: 'Humira',
    scheduledAt: '2024-04-22T08:00:00Z',
    takenAt: null,
    status: 'pending',
    videoId: null,
    notes: null,
  },
];

export const MOCK_ADHERENCE_SUMMARY: AdherenceSummary = {
  subscriberId: 'user-sub-001',
  drugId: 'drug-001',
  drugName: 'Humira',
  medicationCount: 2,
  totalDoses: 8,
  takenDoses: 7,
  adherenceRate: 87.5,
  lastTakenAt: '2024-04-08T08:12:00Z',
};

export type MemberWithSummary = User & { summary: AdherenceSummary };

/** Single employer — HR dashboard sees only their covered lives. */
export const MOCK_MEMBER_SUMMARIES_HR: MemberWithSummary[] = [
  {
    id: 'user-sub-001',
    email: 'jane.doe@acmecorp.com',
    firstName: 'Jane',
    lastName: 'Doe',
    role: 'subscriber',
    createdAt: '2024-01-15T00:00:00Z',
    companyName: 'Acme Corporation',
    summary: MOCK_ADHERENCE_SUMMARY,
  },
  {
    id: 'user-sub-002',
    email: 'mark.smith@acmecorp.com',
    firstName: 'Mark',
    lastName: 'Smith',
    role: 'subscriber',
    createdAt: '2024-02-01T00:00:00Z',
    companyName: 'Acme Corporation',
    summary: {
      subscriberId: 'user-sub-002',
      drugId: 'drug-002',
      drugName: 'Enbrel',
      medicationCount: 1,
      totalDoses: 12,
      takenDoses: 12,
      adherenceRate: 100,
      lastTakenAt: '2024-04-07T10:00:00Z',
    },
  },
  {
    id: 'user-sub-003',
    email: 'priya.patel@acmecorp.com',
    firstName: 'Priya',
    lastName: 'Patel',
    role: 'subscriber',
    createdAt: '2024-03-01T00:00:00Z',
    companyName: 'Acme Corporation',
    summary: {
      subscriberId: 'user-sub-003',
      drugId: 'drug-001',
      drugName: 'Humira',
      medicationCount: 3,
      totalDoses: 6,
      takenDoses: 3,
      adherenceRate: 50,
      lastTakenAt: '2024-03-18T11:30:00Z',
    },
  },
];

/** Many sponsors — PBM book of business. */
export const MOCK_MEMBER_SUMMARIES_PBM: MemberWithSummary[] = [
  ...MOCK_MEMBER_SUMMARIES_HR,
  {
    id: 'user-sub-004',
    email: 'elena.volkov@northwind.com',
    firstName: 'Elena',
    lastName: 'Volkov',
    role: 'subscriber',
    createdAt: '2024-01-20T00:00:00Z',
    companyName: 'Northwind Health',
    summary: {
      subscriberId: 'user-sub-004',
      drugId: 'drug-001',
      drugName: 'Humira',
      medicationCount: 1,
      totalDoses: 10,
      takenDoses: 9,
      adherenceRate: 90,
      lastTakenAt: '2024-04-05T14:00:00Z',
    },
  },
  {
    id: 'user-sub-005',
    email: 'james.okafor@northwind.com',
    firstName: 'James',
    lastName: 'Okafor',
    role: 'subscriber',
    createdAt: '2024-02-10T00:00:00Z',
    companyName: 'Northwind Health',
    summary: {
      subscriberId: 'user-sub-005',
      drugId: 'drug-002',
      drugName: 'Enbrel',
      medicationCount: 2,
      totalDoses: 8,
      takenDoses: 8,
      adherenceRate: 100,
      lastTakenAt: '2024-04-09T09:30:00Z',
    },
  },
  {
    id: 'user-sub-006',
    email: 'sofia.rossi@contoso.com',
    firstName: 'Sofia',
    lastName: 'Rossi',
    role: 'subscriber',
    createdAt: '2024-01-08T00:00:00Z',
    companyName: 'Contoso Benefits',
    summary: {
      subscriberId: 'user-sub-006',
      drugId: 'drug-001',
      drugName: 'Humira',
      medicationCount: 1,
      totalDoses: 14,
      takenDoses: 11,
      adherenceRate: 79,
      lastTakenAt: '2024-04-02T08:00:00Z',
    },
  },
  {
    id: 'user-sub-007',
    email: 'wei.zhang@contoso.com',
    firstName: 'Wei',
    lastName: 'Zhang',
    role: 'subscriber',
    createdAt: '2024-02-22T00:00:00Z',
    companyName: 'Contoso Benefits',
    summary: {
      subscriberId: 'user-sub-007',
      drugId: 'drug-002',
      drugName: 'Enbrel',
      medicationCount: 1,
      totalDoses: 6,
      takenDoses: 5,
      adherenceRate: 83,
      lastTakenAt: '2024-03-28T16:00:00Z',
    },
  },
  {
    id: 'user-sub-008',
    email: 'amina.hassan@contoso.com',
    firstName: 'Amina',
    lastName: 'Hassan',
    role: 'subscriber',
    createdAt: '2024-03-05T00:00:00Z',
    companyName: 'Contoso Benefits',
    summary: {
      subscriberId: 'user-sub-008',
      drugId: 'drug-001',
      drugName: 'Humira',
      medicationCount: 2,
      totalDoses: 4,
      takenDoses: 2,
      adherenceRate: 50,
      lastTakenAt: '2024-03-15T12:00:00Z',
    },
  },
  {
    id: 'user-sub-009',
    email: 'olivia.brown@fabrikam.com',
    firstName: 'Olivia',
    lastName: 'Brown',
    role: 'subscriber',
    createdAt: '2024-01-28T00:00:00Z',
    companyName: 'Fabrikam Medical',
    summary: {
      subscriberId: 'user-sub-009',
      drugId: 'drug-002',
      drugName: 'Enbrel',
      medicationCount: 1,
      totalDoses: 10,
      takenDoses: 10,
      adherenceRate: 100,
      lastTakenAt: '2024-04-10T11:00:00Z',
    },
  },
  {
    id: 'user-sub-010',
    email: 'diego.martinez@fabrikam.com',
    firstName: 'Diego',
    lastName: 'Martinez',
    role: 'subscriber',
    createdAt: '2024-02-14T00:00:00Z',
    companyName: 'Fabrikam Medical',
    summary: {
      subscriberId: 'user-sub-010',
      drugId: 'drug-001',
      drugName: 'Humira',
      medicationCount: 3,
      totalDoses: 12,
      takenDoses: 10,
      adherenceRate: 83,
      lastTakenAt: '2024-04-06T07:00:00Z',
    },
  },
  {
    id: 'user-sub-011',
    email: 'yuki.tanaka@globex.com',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    role: 'subscriber',
    createdAt: '2024-01-11T00:00:00Z',
    companyName: 'Globex Pharma Group',
    summary: {
      subscriberId: 'user-sub-011',
      drugId: 'drug-001',
      drugName: 'Humira',
      medicationCount: 1,
      totalDoses: 8,
      takenDoses: 7,
      adherenceRate: 88,
      lastTakenAt: '2024-04-08T06:00:00Z',
    },
  },
  {
    id: 'user-sub-012',
    email: 'lars.nielsen@globex.com',
    firstName: 'Lars',
    lastName: 'Nielsen',
    role: 'subscriber',
    createdAt: '2024-03-12T00:00:00Z',
    companyName: 'Globex Pharma Group',
    summary: {
      subscriberId: 'user-sub-012',
      drugId: 'drug-002',
      drugName: 'Enbrel',
      medicationCount: 2,
      totalDoses: 5,
      takenDoses: 4,
      adherenceRate: 80,
      lastTakenAt: '2024-04-01T13:00:00Z',
    },
  },
  {
    id: 'user-sub-013',
    email: 'fatima.ali@initech.com',
    firstName: 'Fatima',
    lastName: 'Ali',
    role: 'subscriber',
    createdAt: '2024-02-03T00:00:00Z',
    companyName: 'Initech Wellness',
    summary: {
      subscriberId: 'user-sub-013',
      drugId: 'drug-001',
      drugName: 'Humira',
      medicationCount: 1,
      totalDoses: 9,
      takenDoses: 8,
      adherenceRate: 89,
      lastTakenAt: '2024-04-04T10:00:00Z',
    },
  },
  {
    id: 'user-sub-014',
    email: 'henrik.lindstrom@northwind.com',
    firstName: 'Henrik',
    lastName: 'Lindstrom',
    role: 'subscriber',
    createdAt: '2024-03-20T00:00:00Z',
    companyName: 'Northwind Health',
    summary: {
      subscriberId: 'user-sub-014',
      drugId: 'drug-002',
      drugName: 'Enbrel',
      medicationCount: 1,
      totalDoses: 7,
      takenDoses: 6,
      adherenceRate: 86,
      lastTakenAt: '2024-03-30T15:00:00Z',
    },
  },
  {
    id: 'user-sub-015',
    email: 'kevin.nguyen@acmecorp.com',
    firstName: 'Kevin',
    lastName: 'Nguyen',
    role: 'subscriber',
    createdAt: '2024-02-18T00:00:00Z',
    companyName: 'Acme Corporation',
    summary: {
      subscriberId: 'user-sub-015',
      drugId: 'drug-002',
      drugName: 'Enbrel',
      medicationCount: 1,
      totalDoses: 11,
      takenDoses: 10,
      adherenceRate: 91,
      lastTakenAt: '2024-04-09T08:00:00Z',
    },
  },
];

export const MOCK_VIDEOS: VideoMetadata[] = [
  {
    id: 'vid-001',
    subscriberId: 'user-sub-001',
    adherenceRecordId: 'rec-001',
    storageKey: 'videos/user-sub-001/rec-001.mp4',
    durationSeconds: 14,
    status: 'ready',
    uploadedAt: '2024-04-08T08:13:00Z',
    playbackUrl: 'https://example.com/mock-video-playback',
  },
  {
    id: 'vid-002',
    subscriberId: 'user-sub-001',
    adherenceRecordId: 'rec-002',
    storageKey: 'videos/user-sub-001/rec-002.mp4',
    durationSeconds: 18,
    status: 'ready',
    uploadedAt: '2024-03-25T09:02:00Z',
    playbackUrl: 'https://example.com/mock-video-playback',
  },
];
